name: vtc_application
description: Reservation de VTC.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_svg: ^2.0.4
  fluttertoast: ^8.1.3
  geolocator: ^9.0.2
  http: ^0.13.5
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/images/
